### ISSUE TITLE
Timeutil requirement in Ubuntu 17.04

### ISSUE THREAD

**Issue by htyeim** [rilma/pyIRI2016#5]
Ubuntu 17.04, python 3, anaconda

```
Collecting timeutil (from pyiri2016)
  Could not find a version that satisfies the requirement timeutil (from pyiri2016) (from versions: )
No matching distribution found for timeutil (from pyiri2016)
```

**Comment by rilma** [comment]
It works in Ubuntu 16.04 as you can see it in the CI report included in the repository. Keep in mind that Ubuntu 16.04 is the current LTS edition. It is more stable and I highly recommend it.

**Comment by scivision** [comment]
@htyeim how are you installing? Ubuntu version is irrelevant most likely if you're using the current version obtained from

    git clone https://github.com/rilma/pyIRI2016

    python setup.py develop

This pulls in the current timeUtilities as well automatically.

**Comment by htyeim** [comment]
@scivision Many thanks! 
I found an alternative package (https://github.com/timduly4/pyglow), which provide IRI, HMW, etc.. 
I have modified some code to make it run in python 3 (https://github.com/htyeim/pyglow).

**Comment by rilma** [comment]
This may be evaluated in the upcoming refactored version of the repository content. Closing the issue.
