### ISSUE TITLE
pip install has timeutil.timeutil import error

### ISSUE THREAD

**Issue by Joshuaalbert** [rilma/pyIRI2016#6]
Dear @rilma,

please note that the version installed via `pip install pyiri2016` appears to reference a different structure for timeutil.

For example,

`from pyiri2016 import IRI2016Profile`
 gives traceback
```
~/anaconda3/envs/kerastf/lib/python3.6/site-packages/pyiri2016/__init__.py in <module>()
      6 #%%
      7 from .iriweb import iriwebg
----> 8 from timeutil.timeutil import TimeUtilities
      9 from numpy import arange, nan, ones, squeeze, where
     10 
```

your TimeUtilities is defined in the __init__.py of timeutils so the proper call should be from timeutil import TimeUtilities and indeed your current __init__.py of this package does call this. I suppose pip was not updated to the current version of code.

**Comment by rilma** [comment]
@scivision uploaded the package into the package index and perhaps it lost a track of TimeUtilities updates. You shouldn't get an error if you install (clone) directly from my repository. Maybe you can pull a request solving the issue. Thanks!!!

**Comment by scivision** [comment]
Yes the PyPi version of pyiri2016 1.2.2 is definitely of date. I just looked. 
You need the current version, obtained from

    git clone https://github.com/rilma/TimeUtilities
    python setup.py develop
    https://github.com/rilma/pyIRI2016/
    python setup.py develop

**Comment by fantianxingmie** [comment]
There's no need to reinstall anything. I tried to get rid of the second "timeutil" from the import which turned line 8 to" from timeutil import TimeUtilities", then it's done.

**Comment by rilma** [comment]
Due to lack of PR, closing this issue.
