### ISSUE TITLE
ImportError Traceback 

### ISSUE THREAD

**Issue by 1numco** [rilma/pyIRI2016#8]
Hello!
PyIRI2016 installed successfully. I run your scripts and an error appears:

ImportError Traceback (most recent call last) 
<ipython-input-1-1edaed53afe4> in <module>() 
----> 1 from pyiri2016 import IRI2016Profile 
 2 from numpy import arange 
 3 from matplotlib.pyplot import figure, legend, show 
 4 import seaborn 
 5 
 
~\pyIRI20161\pyiri2016\__init__.py in <module>() 
 5 from pathlib2 import Path 
 6 #%% 
----> 7 from .iriweb import iriwebg 
 8 from timeutil import TimeUtilities 
 9 from numpy import arange, nan, ones, squeeze, where 
 
ImportError: DLL load failed: module was not found

**Comment by bioyesaeed** [comment]
I have a similar issue. Have you managed to resolve it?

**Comment by rilma** [comment]
This problem is due to execution environment. It's going to be resolved in an upcoming refactoring of the project. Closing this issue.
